name: ceciliaweckstrom
favicon: null
layout_spectrum: 0.26169801433570683
typography_spectrum: 0.05781354778446257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2577229952439666
  lightness: 0.3509877431206405
  saturation: 0.5781232863664627
  rhythmicContrast: 0.8971617994830012
purpose: []
